apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-dep
  name: my-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-dep
  strategy: {}
  template:
    metadata:
      labels:
        app: my-dep
    spec:
      containers:
      - image: busybox:latest
        name: busybox
        resources: {}
      - image: ubuntu:latest
        name: ubuntu
        resources: {}
      - image: nginx
        name: nginx
        resources: {}
